import = [
    "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
]

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 14

[colors]
draw_bold_text_with_bright_colors = true
